onlineFriendList = {
	name1: 'Meg Lanning (c)',
	name2: 'Alex Blackwell',
	name3: 'Kristen Beams',
	name4: 'Nicole Bolton',
	name5: 'Jessica Cameron',
	name6: 'Sarah Coyte',
	name7: 'Rene Farrell',
	name8: 'Holly Ferling',
	name9: 'Grace Harris',
	name10: 'Alyssa Healy',
	name11: 'Julie Hunter',
	name12: 'Jess Jonassen',
	name13: 'Delissa Kimmince',
	name14: 'Erin Osborne',
	name15: 'Ellyse Perry',
	name16: 'Megan Schutt',
	name17: 'Elyse Villani',
    count:17
}