searchList = {
  name1: 'Alan, Allan',
  pic1: 'tariq.jpg',
  city1: 'Islamabad',
  education1: 'BSCS',
  name2: 'Alan, Allan',
  pic2: 'tariq.jpg',
  city2: 'Islamabad',
  education2: 'BSCS', 
  name3: 'Alan, Allan',
  pic3: 'tariq.jpg',
  city3: 'Islamabad',
  education3: 'BSCS',
  name3: 'Alan, Allan',
  pic3: 'tariq.jpg',
  city3: 'Islamabad',
  education3: 'BSCS',  
  name4: 'Alan, Allan',
  pic4: 'tariq.jpg',
  city4: 'Islamabad',
  education4: 'BSCS',    
  name5: 'Alan, Allan',
  pic5: 'tariq.jpg',
  city5: 'Islamabad',
  education5: 'BSCS',
  name6: 'Alan, Allan',
  pic6: 'tariq.jpg',
  city6: 'Islamabad',
  education6: 'BSCS',  
  name7: 'Alan, Allan',
  pic7: 'tariq.jpg',
  city7: 'Islamabad',
  education7: 'BSCS',
  name8: 'Alan, Allan',
  pic8: 'tariq.jpg',
  city8: 'Islamabad',
  education8: 'BSCS',  
  name9: 'Alan, Allan',
  pic9: 'tariq.jpg',
  city9: 'Islamabad',
  education9: 'BSCS',  
  name10: 'Alan, Allan',
  pic10: 'tariq.jpg',
  city10: 'Islamabad',
  education10: 'BSCS',  
  count: 10
  
}